"use strict";
/* 详细教学文案在 i18n.js 构建字典之前注册；与行程业务数据隔离。 */
(() => {
  const content = [
    {
      howto: [
        ['日期与天数：先填写抵达日期、时刻和 1～15 天的行程长度；这些信息用于安排每天的可用时间。', 'Dates and duration: enter your arrival date, time and a trip length of 1–15 days. These determine the available time each day.', '日程と日数：到着日・時刻と1～15日間の旅行日数を入力します。各日に使える時間の計算に使われます。', '날짜와 일수: 도착 날짜, 시간, 1~15일의 여행 기간을 입력하세요. 하루에 사용할 수 있는 시간을 계산하는 데 쓰여요.'],
        ['口岸与住宿：搜索抵达的机场或车站，再从搜索结果中选择；住宿填写已经预订的酒店或民宿，不是在这里订房。', 'Arrival and accommodation: search for your airport or station, then select a result. Choose the hotel or guesthouse you have already booked; this page does not book accommodation.', '到着地点と宿泊先：空港や駅を検索し、結果から選択します。予約済みのホテルや民宿を選んでください。この画面で宿泊予約はできません。', '도착지와 숙소: 공항이나 역을 검색한 뒤 검색 결과에서 선택하세요. 이미 예약한 호텔이나 숙소를 고르는 것이며, 여기서 숙소를 예약하지는 않아요.'],
        ['兴趣与节奏：兴趣影响推荐排序；轻松、均衡、紧凑决定建议景点数量，建议数量不是禁止继续添加的上限。', 'Interests and pace: interests affect recommendation order. A relaxed, balanced or packed pace changes the suggested number of attractions; you can still add more.', '興味とペース：興味はおすすめの順番に影響します。ゆったり・標準・詰め込みで推奨する観光地数が変わりますが、追加を禁止する上限ではありません。', '관심사와 속도: 관심사는 추천 순서에 영향을 줘요. 여유롭게, 균형 있게, 빡빡하게에 따라 권장 관광지 수가 달라지지만 추가가 금지되는 상한은 아니에요.'],
        ['预算与返程：预算是每人整趟金额，可留空；外币需确认汇率。返程安排可选，填好后点击“保存行程”。', 'Budget and return: the budget is per person for the whole trip and can be blank. Confirm the exchange rate for foreign currencies. Return details are optional; then select “Save trip”.', '予算と帰路：予算は一人あたりの旅行全体の金額で、未入力でも構いません。外貨は換算レートを確認します。帰路の情報は任意です。最後に「行程を保存」を押します。', '예산과 귀국: 예산은 1인당 전체 여행 금액이며 비워둘 수 있어요. 외화를 선택하면 환율을 확인하세요. 귀국 정보는 선택 사항이고, 입력 후 ‘여행 저장’을 누르세요.'],
      ],
      example: ['例如：两人同行、上海 3 天、14:00 抵达，选择已订酒店与均衡节奏，每人预算 3000 元。这里的 3000 元是每人的三天总预算，不是两人合计，也不是每天预算。', 'Example: two travelers, 3 days in Shanghai, arrival at 14:00, a booked hotel and a balanced pace, with a CNY 3,000 budget per person. This is each person’s total for three days, not a shared or daily budget.', '例：2人で上海に3日間、14:00到着、予約済みホテル、標準ペース、一人3,000元の予算とします。3,000元は一人の3日間の合計で、2人分の合計や一日分ではありません。', '예시: 두 명이 상하이에서 3일 여행하며 14:00에 도착해요. 예약한 호텔, 균형 있는 속도, 1인당 예산 3,000위안을 선택해요. 3,000위안은 한 사람의 3일 총예산이며 두 명 합계나 하루 예산이 아니에요.'],
      faq: [
        {question:['输入了酒店名称，为什么仍提示选择住宿？', 'Why am I asked to select accommodation after typing its name?', 'ホテル名を入力したのに、宿泊先の選択を求められるのはなぜ？', '호텔 이름을 입력했는데 왜 숙소를 선택하라고 하나요?'], answer:['搜索框用于筛选，不等于已经选中。请再选择下方的住宿搜索结果；没有结果时检查拼写或换用中文、英文、拼音关键词。', 'Typing only filters the list; it does not select a place. Select a result below the search box. If there are no results, check spelling or try Chinese, English or pinyin keywords.', '検索欄への入力は候補の絞り込みです。下の検索結果から宿泊先を選んでください。候補がなければ、綴りを確認するか中国語・英語・ピンインで検索します。', '검색창 입력은 목록을 거르는 것이지 선택을 완료하는 것은 아니에요. 아래 검색 결과에서 숙소를 선택하세요. 결과가 없으면 철자를 확인하거나 중국어, 영어, 병음으로 검색하세요.']},
        {question:['保存后还能改日期、酒店或预算吗？', 'Can I change dates, accommodation or budget after saving?', '保存後に日程・ホテル・予算を変更できますか？', '저장 후 날짜, 호텔, 예산을 바꿀 수 있나요?'], answer:['可以。展开行程设定修改后再次保存，会更新当前行程。日期或住宿改变可能影响每日起终点、交通和费用；修改后请重新检查。', 'Yes. Expand trip setup, edit the fields and save again to update the current trip. Date or accommodation changes may affect daily endpoints, transport and costs, so review them afterward.', 'できます。行程設定を開いて変更し、再保存すると現在の行程が更新されます。日程や宿泊先の変更は各日の起終点・移動・費用に影響するため、再確認してください。', '네. 여행 설정을 펼쳐 수정하고 다시 저장하면 현재 여행이 업데이트돼요. 날짜나 숙소 변경은 일일 출발·도착지, 교통, 비용에 영향을 줄 수 있으니 다시 확인하세요.']},
      ],
    },
    {
      howto: [
        ['推荐方式：在行程设定里勾选想安排的日期，再点击“生成推荐行程”；生成结果可在每日行程继续修改。', 'Recommended itinerary: select the days to plan in trip setup, then choose “Generate itinerary”. You can edit the result in the daily itinerary.', 'おすすめを使う場合：行程設定で対象の日を選び、「おすすめ行程を生成」を押します。結果は日別行程で編集できます。', '추천 이용: 여행 설정에서 계획할 날짜를 선택한 뒤 ‘추천 일정 생성’을 누르세요. 결과는 일일 일정에서 수정할 수 있어요.'],
        ['短行程：1～2 天默认不会勾选日期，需要自己勾选；更长行程默认选择中间日期，抵达日和返程日可按需加入。', 'Short trips: 1–2 day trips have no days selected by default, so select them yourself. Longer trips default to the middle days; you may also select arrival and return days.', '短い旅行：1～2日間は日付が初期選択されないため、自分で選びます。長い旅行では中間の日が初期選択され、到着日・帰国日も追加できます。', '짧은 여행: 1~2일 여행은 날짜가 기본 선택되지 않으니 직접 선택하세요. 긴 여행은 중간 날짜가 기본 선택되며 도착일과 귀국일도 추가할 수 있어요.'],
        ['手动方式：在挑选景点里搜索或筛选类别，打开景点详情，查看开放与预约信息，选择加入哪一天并点击“加入行程”。', 'Manual selection: search or filter attractions, open a detail view and check opening and booking information. Choose a day, then select “Add to trip”.', '手動で選ぶ場合：観光地を検索・絞り込み、詳細で営業・予約情報を確認します。追加先の日を選び、「行程に追加」を押します。', '직접 선택: 관광지를 검색하거나 분류로 필터링하고 상세 정보에서 운영·예약 정보를 확인하세요. 추가할 날짜를 선택하고 ‘여행에 추가’를 누르세요.'],
        ['保留与调整：推荐只填所选空白日，已有安排会保留；不喜欢的景点可移除、换日期或手动补充。', 'Keep and adjust: recommendations fill selected empty days and preserve existing plans. Remove attractions you dislike, move them to another day or add your own choices.', '既存の予定と調整：おすすめは選択した空白の日に追加され、既存の予定は保たれます。観光地の削除・日付変更・手動追加ができます。', '기존 일정과 조정: 추천은 선택한 빈 날짜만 채우고 기존 일정은 유지해요. 마음에 들지 않는 관광지는 삭제하거나 날짜를 옮기고 직접 추가할 수 있어요.'],
      ],
      example:['例如：3 天行程默认可推荐第 2 天。第 1 天只想抵达后散步，就手动给第 1 天加一个景点；如果只有 2 天，需要主动勾选想生成推荐的日期。', 'Example: a 3-day trip defaults to recommendations for day 2. Add one attraction manually to day 1 if you only want a walk after arrival. For a 2-day trip, explicitly select the days you want recommended plans for.', '例：3日間の旅行では2日目がおすすめの初期対象です。到着日は散歩だけにしたい場合、1日目に観光地を一つ手動追加します。2日間なら対象の日を自分で選んでください。', '예시: 3일 여행은 2일차가 추천 기본 대상이에요. 도착 후 산책만 하고 싶다면 1일차에 관광지 하나를 직접 추가하세요. 2일 여행은 추천할 날짜를 직접 선택해야 해요.'],
      faq:[
        {question:['为什么推荐按钮不可用，或没有新增景点？', 'Why is generation unavailable or adding no attractions?', 'おすすめを生成できない、または追加されないのはなぜ？', '왜 추천 버튼을 사용할 수 없거나 관광지가 추가되지 않나요?'],answer:['先看按钮附近的提示：可能没有勾选日期、所选日期已有安排，或推荐服务未就绪。确认日期和设定；服务未就绪时仍可手动安排。', 'Read the message near the button. No days may be selected, selected days may already have plans, or the recommendation service may be unavailable. Check dates and settings; manual planning remains possible.', 'ボタン付近の説明を確認してください。日付未選択、対象日に予定がある、またはおすすめ機能が利用できない場合があります。日付と設定を確認し、利用不可なら手動で追加できます。', '버튼 근처의 안내를 확인하세요. 날짜가 선택되지 않았거나 선택한 날짜에 이미 일정이 있거나 추천 서비스가 준비되지 않았을 수 있어요. 날짜와 설정을 확인하고, 추천을 사용할 수 없으면 직접 계획하세요.']},
        {question:['加入景点时提示冲突，应该怎么处理？', 'What should I do if adding an attraction shows a conflict?', '観光地の追加時に競合が表示されたら？', '관광지 추가 시 충돌이 표시되면 어떻게 하나요?'],answer:['先读冲突原因，核对开放时间与当天安排。可以改日期或换景点；确实要保留时再使用页面的确认入口，不要把提示当成已经解决。', 'Read the reason and check opening hours and that day’s plans. Change the day or attraction if needed. Use the confirmation action only if you decide to keep it; the warning itself does not resolve the conflict.', '理由を読み、営業時間と当日の予定を確認します。日付や観光地を変更できます。残すと判断した場合のみ確認操作を行ってください。警告が出ただけでは解決していません。', '충돌 이유를 읽고 운영 시간과 당일 일정을 확인하세요. 날짜나 관광지를 바꿀 수 있어요. 유지하기로 결정한 경우에만 확인 기능을 사용하세요. 안내가 표시된 것만으로 충돌이 해결되지는 않아요.']},
      ],
    },
    {
      howto:[
        ['展开日期卡片：先看每天的起点、终点和出发时间，确认住宿与口岸安排符合实际。', 'Expand a day card: check its start, end and departure time, and confirm that accommodation and gateway stops match your plans.', '日付カードを開く：出発・到着地点と出発時刻を確認し、宿泊先や空港・駅が実際の予定に合っているか確認します。', '날짜 카드 펼치기: 출발지, 도착지, 출발 시간을 확인하고 숙소와 공항·역 일정이 실제 계획과 맞는지 확인하세요.'],
        ['调整景点：用上移、下移或拖动改变顺序；锁定保护已固定点位的相对顺序，跨天移动前需先解锁。', 'Adjust attractions: move them up, down or drag to reorder. Locking protects the relative order of locked stops; unlock a stop before moving it to another day.', '観光地を調整：上下移動やドラッグで順番を変更します。ロックは固定した地点同士の相対順序を保ちます。別の日に移す前に解除してください。', '관광지 조정: 위로, 아래로 이동하거나 끌어 순서를 바꾸세요. 잠금은 잠긴 장소 사이의 상대 순서를 보호해요. 다른 날로 옮기려면 먼저 잠금을 해제하세요.'],
        ['添加住宿或口岸：途中休息只影响当天停留；过夜或更换住宿会影响后续默认住宿，两者不要混用。', 'Add accommodation or gateway stops: a rest stop only affects that day’s stay. An overnight stay or accommodation change affects later default accommodation; choose the intended purpose.', '宿泊先や空港・駅を追加：途中の休憩は当日の滞在だけに影響します。宿泊・宿泊先変更は後の日の既定宿泊先に影響するため、用途を選び分けます。', '숙소 또는 공항·역 추가: 중간 휴식은 당일 체류에만 영향을 줘요. 숙박이나 숙소 변경은 이후 기본 숙소에 영향을 주므로 용도를 구분하세요.'],
        ['计算与选择交通：点击“计算全部区间交通”，在每日卡片查看可用方案。换日期、改顺序或换酒店后，重新计算受影响的交通。', 'Calculate and choose transport: select “Calculate all transfers” and review options in each day card. Recalculate affected transfers after changing dates, order or accommodation.', '移動を計算・選択：「全区間の移動を計算」を押し、各日で利用可能な案を確認します。日付・順番・ホテルの変更後は影響する移動を再計算します。', '교통 계산과 선택: ‘전체 구간 교통 계산’을 누르고 날짜 카드에서 가능한 경로를 확인하세요. 날짜, 순서, 호텔을 변경한 뒤에는 해당 교통을 다시 계산하세요.'],
      ],
      example:['例如：一天原来是“酒店 → 景点 A → 景点 B → 酒店”。把 B 移到 A 前面，或把当天终点换成另一家酒店后，旧交通时间不能直接沿用，应重新计算。', 'Example: a day is “Hotel → Attraction A → Attraction B → Hotel”. After moving B before A or changing the final hotel, recalculate rather than reusing the old travel times.', '例：「ホテル → 観光地A → 観光地B → ホテル」の日に、BをAの前に移す、または最後のホテルを変えた場合、以前の移動時間をそのまま使わず再計算します。', '예시: 하루 일정이 ‘호텔 → 관광지 A → 관광지 B → 호텔’이라면, B를 A 앞으로 옮기거나 마지막 호텔을 바꾼 후에는 이전 이동 시간을 그대로 사용하지 말고 다시 계산하세요.'],
      faq:[
        {question:['计算按钮不可用，或某种交通方案失败怎么办？', 'What if calculation is unavailable or a transport option fails?', '計算できない、または交通案の取得に失敗したら？', '계산 버튼을 사용할 수 없거나 교통 경로가 실패하면 어떻게 하나요?'],answer:['查看按钮附近与当天交通区的原因提示。先加入景点或设定不同起终点；交通服务不可用时需要恢复服务。单种方式失败时，查看其他可用方案或稍后重试。', 'Read the explanation near the button and in that day’s transport section. Add attractions or different endpoints first. An unavailable transport service must be restored; if one mode fails, review other options or retry later.', 'ボタン付近と各日の移動欄の理由を確認します。まず観光地や異なる起終点を設定してください。移動機能が利用不可なら復旧が必要です。一つの手段だけ失敗した場合は別の案を確認するか再試行します。', '버튼 근처와 당일 교통 영역의 이유를 확인하세요. 먼저 관광지를 추가하거나 서로 다른 출발·도착지를 설정하세요. 교통 서비스가 없으면 복구해야 하고, 한 이동 수단만 실패하면 다른 경로를 보거나 나중에 재시도하세요.']},
        {question:['在酒店停留休息，会被重复计算房费吗？', 'Does resting at a hotel add another accommodation charge?', 'ホテルで休憩すると宿泊費が重複しますか？', '호텔에서 쉬면 숙박비가 중복 계산되나요?'],answer:['选择“途中休息”只增加停留时间，不改变后续住宿，也不重复计房费。实际换酒店过夜时选择过夜用途，并核对费用评估中的房晚。', 'A rest stop adds stay time without changing later accommodation or charging another room night. For an actual overnight hotel change, choose the overnight purpose and check the room nights in the cost estimate.', '「途中の休憩」は滞在時間だけを追加し、後の宿泊先を変えず、宿泊費も重複しません。実際に泊まるホテルを変える場合は宿泊用途を選び、費用の宿泊数を確認してください。', '‘중간 휴식’은 체류 시간만 추가하고 이후 숙소를 바꾸거나 숙박비를 중복 계산하지 않아요. 실제로 호텔을 바꿔 숙박한다면 숙박 용도를 선택하고 비용 평가에서 숙박 일수를 확인하세요.']},
      ],
    },
    {
      howto:[
        ['查看行程提醒：读清闭馆、预约、亮灯和时间风险的原因，使用调整入口回到对应日期；改完后点击“重新检查”。', 'Review reminders: read the reasons for closure, booking, lighting and timing warnings. Use an adjustment link to return to the relevant day, then check again after editing.', '注意事項を確認：休館・予約・点灯・時刻の警告理由を読み、調整リンクで該当日に戻ります。変更後は再チェックしてください。', '알림 확인: 휴관, 예약, 점등, 시간 위험의 이유를 읽고 조정 기능으로 해당 날짜로 돌아가세요. 수정 후 다시 확인하세요.'],
        ['展开费用评估：摘要是每人整趟费用，展开后看分类、参考来源、待补充项和预算差额。', 'Expand the cost estimate: the summary is for the whole trip per person. Review categories, sources, missing amounts and the budget difference.', '費用見積もりを開く：概要は一人あたりの旅行全体の費用です。分類・参考情報・未入力項目・予算との差を確認します。', '비용 평가 펼치기: 요약은 1인당 전체 여행 비용이에요. 분류, 참고 출처, 미입력 항목, 예산 차이를 확인하세요.'],
        ['确认人数与住宿：填写实际同行人数与房间数；自动住宿通常按前 N−1 晚估算，提前入住、延住或跨零点情况要按实际房晚调整。', 'Confirm travelers and rooms: enter actual traveler and room counts. Automatic lodging usually uses the first N−1 nights; adjust paid nights for early check-in, extended stays or arrivals after midnight.', '人数と宿泊を確認：実際の同行人数と部屋数を入力します。自動宿泊は通常、最初のN−1泊で見積もるため、早めの入室・延泊・日付をまたぐ到着は実際の泊数に調整してください。', '인원과 숙박 확인: 실제 여행 인원과 객실 수를 입력하세요. 자동 숙박은 보통 앞의 N−1박으로 추정하므로 조기 체크인, 연장 숙박, 자정 이후 도착은 실제 숙박 수로 조정하세요.'],
        ['补全实际费用：门票留空沿用参考价，手填金额优先，0 表示免费；餐饮、往返机票与其他费用按页面的每人或每天口径填写。', 'Complete actual costs: a blank ticket amount uses the reference price, an entered amount overrides it and 0 means free. Enter meals, return flights and other costs using the per-person or per-day units shown.', '実際の費用を補う：入場料が空欄なら参考価格を使い、入力値が優先され、0は無料を意味します。食事・往復航空券などは画面の一人あたり・一日あたりの単位に従ってください。', '실제 비용 보완: 입장료를 비워두면 참고 가격을 사용하고 직접 입력한 금액이 우선하며, 0은 무료를 뜻해요. 식비, 왕복 항공료 등은 화면에 표시된 1인당 또는 일일 단위로 입력하세요.'],
      ],
      example:['例如：2 人住 1 间房，假设实际房价每间每晚 600 元、住 2 晚，则住宿共 1200 元，分摊后每人 600 元。这个数字仅说明分摊方法，不是酒店报价。', 'Example: two people share one room. At an assumed CNY 600 per room per night for two nights, lodging totals CNY 1,200, or CNY 600 per person. This illustrates cost sharing, not a hotel quote.', '例：2人で1室、仮に1室1泊600元で2泊なら宿泊費は計1,200元、一人600元です。これは割り勘の説明で、ホテルの見積価格ではありません。', '예시: 두 명이 객실 하나를 사용하고, 가정한 객실 가격이 1박 600위안이며 2박이라면 총 1,200위안, 1인당 600위안이에요. 분담 방법을 설명하는 숫자이며 호텔 견적이 아니에요.'],
      faq:[
        {question:['“费用待补充”是不是代表预算一定够用？', 'Does “missing costs” mean my budget is enough?', '「費用未入力」なら予算は足りていますか？', '‘비용 미입력’이면 예산이 충분하다는 뜻인가요?'],answer:['不是。已计入金额只包含已知费用，缺少餐饮、门票或交通等项目时还不能判断整趟总价。先补全费用，再看预算状态与差额。', 'No. The recorded total includes only known costs. Missing meals, tickets or transport prevent a complete trip estimate. Fill them in before assessing your budget and remaining amount.', 'いいえ。計上済み金額には既知の費用だけが含まれます。食事・入場料・移動費などが不足すると総額は判断できません。補ってから予算の状態と差額を確認してください。', '아니에요. 반영된 금액에는 알려진 비용만 포함돼요. 식비, 입장료, 교통비 등이 없으면 전체 비용을 판단할 수 없어요. 먼저 비용을 채운 뒤 예산 상태와 차이를 확인하세요.']},
        {question:['提示需要核实开放信息，软件已经替我预约了吗？', 'Does an opening-information reminder mean I have a booking?', '営業情報の確認が出たら、予約も済んでいますか？', '운영 정보 확인 알림이 있으면 예약도 된 건가요?'],answer:['没有。这里提供规划提醒，不会替你购买门票、预订酒店或完成景点预约；请按景点官方信息自行确认与预订。', 'No. These are planning reminders. The workbench does not buy tickets, reserve accommodation or book attractions for you; confirm and book using the attraction’s official information.', 'いいえ。これは計画用の注意事項です。入場券の購入、ホテルや観光地の予約は行いません。公式情報で確認し、自分で予約してください。', '아니에요. 계획을 위한 알림이며 입장권 구매, 호텔 예약, 관광지 예약을 대신하지 않아요. 공식 정보를 확인하고 직접 예약하세요.']},
      ],
    },
    {
      howto:[
        ['生成前：检查每日起终点和交通，补齐缺失时间，并处理尚未确认的冲突，再点击“生成离线包”。', 'Before generating: check daily endpoints and transport, fill missing times and handle unconfirmed conflicts, then choose “Generate offline package”.', '生成前：各日の起終点と移動を確認し、不足する時刻と未確認の競合を処理してから「オフラインパッケージを生成」を押します。', '생성 전: 일일 출발·도착지와 교통을 확인하고 누락된 시간, 미확인 충돌을 처리한 뒤 ‘오프라인 패키지 생성’을 누르세요.'],
        ['下载到设备：点击“下载问路卡 HTML”，找到下载文件并打开一次；只看到网页预览不等于已经保存文件。', 'Download to your device: choose “Download directions HTML”, locate the downloaded file and open it once. Seeing the preview alone does not mean the file is saved.', '端末に保存：「道案内HTMLをダウンロード」を押し、保存されたファイルを見つけて一度開きます。画面のプレビューを見るだけでは保存されません。', '기기에 저장: ‘길 안내 HTML 다운로드’를 누르고 다운로드한 파일을 찾아 한 번 열어보세요. 웹 미리보기가 보이는 것만으로 파일이 저장된 것은 아니에요.'],
        ['离线使用：打开下载的 HTML，查看每日行程、时间与交通。中文地名和中文问路卡可以展示给当地人。', 'Use offline: open the downloaded HTML to view daily plans, times and transport. Show Chinese place names and direction cards to locals when asking for help.', 'オフラインで使う：保存したHTMLを開き、日別の行程・時刻・移動を確認します。中国語の地名と道案内カードを現地の人に見せられます。', '오프라인 사용: 다운로드한 HTML을 열어 일일 일정, 시간, 교통을 확인하세요. 중국어 지명과 길 안내 카드를 현지인에게 보여줄 수 있어요.'],
        ['更新文件：改日期、景点或交通后重新生成并下载；手机需要自己保存这份文件，电脑上的下载不会自动同步到手机。', 'Update the file: generate and download again after changing dates, attractions or transport. Save a copy on your phone yourself; a computer download does not sync automatically.', 'ファイルを更新：日付・観光地・移動を変更したら再生成・再保存します。スマートフォンには自分でファイルを保存してください。パソコンの保存は自動同期されません。', '파일 업데이트: 날짜, 관광지, 교통을 바꾸면 다시 생성하고 다운로드하세요. 휴대폰에도 직접 파일을 저장해야 하며 컴퓨터의 다운로드가 자동 동기화되지는 않아요.'],
      ],
      example:['例如：先在电脑生成并下载问路卡，把文件传到手机，在手机上打开确认可读；最后更换酒店后，应重新生成最新问路包，并替换手机上的旧文件。', 'Example: generate and download the directions on your computer, transfer the file to your phone and check that it opens there. After a hotel change, generate a new package and replace the old phone copy.', '例：パソコンで道案内を生成・保存し、スマートフォンに転送して開けることを確認します。ホテルを変更したら最新パッケージを作り、スマートフォンの古いファイルを置き換えてください。', '예시: 컴퓨터에서 길 안내를 생성·다운로드하고 휴대폰으로 파일을 옮겨 열리는지 확인하세요. 호텔을 변경하면 최신 패키지를 생성하고 휴대폰의 이전 파일을 교체하세요.'],
      faq:[
        {question:['离线包为什么不能生成或下载？', 'Why can’t I generate or download the package?', 'パッケージを生成・保存できないのはなぜ？', '왜 패키지를 생성하거나 다운로드할 수 없나요?'],answer:['先读离线区域的提示。未处理冲突、缺少交通时间或离线服务不可用时，需要先解决对应问题。行程更新后旧包也可能无法下载，应重新生成。', 'Read the message in the offline section. Resolve unhandled conflicts, missing travel times or an unavailable offline service first. After trip changes, the old package may also be invalid for download; generate a new one.', 'オフライン欄の説明を確認します。未処理の競合、移動時間の不足、オフライン機能の利用不可を先に解決してください。行程更新後は古いパッケージを保存できない場合があるため、再生成します。', '오프라인 영역의 안내를 읽으세요. 미처리 충돌, 누락된 이동 시간, 오프라인 서비스 문제를 먼저 해결해야 해요. 여행이 바뀌면 이전 패키지를 다운로드할 수 없을 수 있으니 다시 생성하세요.']},
        {question:['浏览器缓存、网页预览和下载文件有什么区别？', 'How do browser cache, preview and downloaded files differ?', 'ブラウザーのキャッシュ・プレビュー・保存ファイルの違いは？', '브라우저 캐시, 미리보기, 다운로드 파일은 어떻게 다른가요?'],answer:['预览只是在当前网页查看；缓存保存在当前浏览器，可能因过期或清理数据失效。下载的 HTML 是独立文件，关闭本地服务也能打开，更适合出发前保存。', 'Preview shows the package on the current page. Cache belongs to the current browser and can expire or be cleared. Downloaded HTML is a standalone file that works after the local service is closed, making it useful to save before departure.', 'プレビューは現在の画面で見るものです。キャッシュは現在のブラウザーに保存され、有効期限やデータ削除で失われます。保存したHTMLは独立したファイルで、ローカルサービス停止後も開けるため、出発前の保存に適しています。', '미리보기는 현재 웹페이지에서 보는 것이에요. 캐시는 현재 브라우저에 저장되며 만료되거나 삭제될 수 있어요. 다운로드한 HTML은 독립 파일로 로컬 서비스가 꺼져도 열 수 있어 출발 전 저장에 적합해요.']},
      ],
    },
  ];
  const register = row => { window.IRLanguageCatalog.push(row); return row[0]; };
  window.IROnboardingContent = content.map(step => ({
    howto: step.howto.map(register), example: register(step.example),
    faq: step.faq.map(item => ({question:register(item.question), answer:register(item.answer)})),
  }));
})();
